# FPL Synthetic Data Generation Configuration
# Pole type configurations - Choose what you want to generate!
pole_framing_types:
  modified_vertical:
    enabled: true    # Enable/disable all modified vertical poles
    configurations:
      - aetx_with_ats:     # AETX configs with ATS
          enabled: true
          components:
            - aetx: true
            - ats: true
      - aetx_with_fuse:    # AETX configs with Fuse
          enabled: true
          components:
            - aetx: true
            - fuse: true
      - surge_arrester:    # Surge Arrester configs
          enabled: true
          components:
            - surge_arresters: true
      - fci:               # FCI configs
          enabled: true
          components:
            - fci: true
      - als:               # ALS configs
          enabled: true
          components:
            - als: true
      - double_als:        # 2x ALS configs
          enabled: true
          components:
            - als: true
            - double_als: true

  vertical:
    enabled: true    # Enable/disable all vertical poles
    configurations:
      - aetx_with_ats:    # AETX with ATS
          enabled: true
          components:
            - aetx: true
            - ats: true
      - aetx_with_fuse:   # AETX with Fuse
          enabled: true
          components:
            - aetx: true
            - fuse: true
      - surge_arrester:   # Surge arrester configs
          enabled: true
          components:
            - surge_arresters: true
      - fci:              # FCI config
          enabled: true
          components:
            - fci: true
      - chicken_support:  # Chicken support bracket
          enabled: true
          components:
            - chicken_support_bracket: true

  crossarm:
    enabled: true    # Enable/disable all crossarm poles
    configurations:
      - afs:             # AFS config
          enabled: true
          components:
            - afs: true
      - double_crossarm: # Double Crossarm config
          enabled: true
          components:
            - double_crossarm: true
          variations:
            - with_fuse:
                enabled: true
                components:
                  - fuse: true
            - with_als:
                enabled: true
                components:
                  - als: true

  deadend:
    enabled: true    # Enable/disable deadend poles
    configurations:
      - standard:          # Standard deadend
          enabled: true
          
  double_deadend:
    enabled: true    # Enable/disable double deadend poles
    configurations:
      - standard:          # Standard double deadend
          enabled: true
          components:
            - double_deadend: true
      - with_oh_switch:    # Double deadend with OH switch
          enabled: true
          components:
            - double_deadend: true
            - oh_switch: true

# Common settings - Adjust these as needed!
components:
  aetx:
    enable_chance: 0.5    # How often to include AETX
    min_phases: 2         # Minimum phases needed
  
  surge_arresters:
    enable_chance: 0.5    # How often to include surge arresters
  
  fci:
    enable_chance: 0.4    # How often to include FCI
    min_phases: 3         # Only on 3-phase poles
  
  chicken_support:
    enable_chance: 0.2    # How often to include support bracket
    excluded_materials: ['concrete']  # Not for concrete poles

  als:
    enable_chance: 0.4    # How often to include ALS
    double_als_chance: 0.3  # How often to make it double

# Choose your materials
pole_materials:
  wood      
    percentage: 50    # 70% wood poles
  concrete:
    percentage: 50    # 30% concrete poles

# Choose number of phases
phases:
  single_phase: 33    # 20% single phase
  two_phase: 33      # 30% two phase
  three_phase: 33    # 50% three phase

# Rendering settings - Adjust as needed!
rendering:
  resolution: [1920, 1080]
  samples: 1056
  denoise: true
  
  camera:
    min_distance: 10
    max_distance: 20
    height_range: [5, 15]
    angle_range: [-30, 30]
  
  output:
    format: "png"
    quality: 100
    save_masks: true
    save_metadata: true